//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.MainWindowMenuSample
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class MainWindowMenuSample { }
#else

	public class MainWindowMenuSample : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public MainWindowMenuSample()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Registry;component/SampleData/MainWindowMenuSample/MainWindowMenuSample.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private MenuCommandsItems _MenuCommandsItems = new MenuCommandsItems();

		public MenuCommandsItems MenuCommandsItems
		{
			get
			{
				return this._MenuCommandsItems;
			}
		}
	}

	public class MenuCommandsItemsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Item = string.Empty;

		public string Item
		{
			get
			{
				return this._Item;
			}

			set
			{
				if (this._Item != value)
				{
					this._Item = value;
					this.OnPropertyChanged("Item");
				}
			}
		}
	}

	public class MenuCommandsItems : System.Collections.ObjectModel.ObservableCollection<MenuCommandsItemsItem>
	{ 
	}
#endif
}
