//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DatabaseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DatabaseSettings defaultInstance = ((DatabaseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DatabaseSettings())));
        
        public static DatabaseSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n-- Creating table \'AddressSet\'\r\nCREATE TABLE [AddressSet] (\r\n    [Id] INTEGER P" +
            "RIMARY KEY NOT NULL,\r\n    [address] nvarchar(2147483647)  NOT NULL,\r\n    [city] " +
            "nvarchar(2147483647)  NOT NULL,\r\n    [postalcode] nvarchar(2147483647)  NOT NULL" +
            ",\r\n    [country] nvarchar(2147483647)  NOT NULL\r\n);\r\n\r\n-- Creating table \'Member" +
            "DetaisSet\'\r\nCREATE TABLE [MemberDetaisSet] (\r\n    [Id] INTEGER PRIMARY KEY NOT N" +
            "ULL,\r\n    [memberno] nvarchar(2147483647)  NOT NULL,\r\n    [memberclass] nvarchar" +
            "(2147483647)  NOT NULL,\r\n    [membergroup] nvarchar(2147483647)  NOT NULL,\r\n    " +
            "[memberjob] nvarchar(2147483647)  NOT NULL,\r\n    [joindate] nvarchar(2147483647)" +
            "  NOT NULL,\r\n    [exitdate] nvarchar(2147483647)  NOT NULL,\r\n    [changeddate] n" +
            "varchar(2147483647)  NOT NULL,\r\n    [paymentstatus] nvarchar(2147483647)  NOT NU" +
            "LL\r\n);\r\n\r\n-- Creating table \'OrganizationSet\'\r\nCREATE TABLE [OrganizationSet] (\r" +
            "\n    [Id] INTEGER PRIMARY KEY NOT NULL,\r\n    [key] nvarchar(2147483647)  NOT NUL" +
            "L,\r\n    [value] nvarchar(2147483647)  NOT NULL\r\n);\r\n\r\n-- Creating table \'Changel" +
            "ogSet\'\r\nCREATE TABLE [ChangelogSet] (\r\n    [Id] INTEGER PRIMARY KEY NOT NULL,\r\n " +
            "   [action] nvarchar(2147483647)  NOT NULL,\r\n    [newvalue] nvarchar(2147483647)" +
            "  NOT NULL,\r\n    [oldvalue] nvarchar(2147483647)  NOT NULL,\r\n    [memberid] nvar" +
            "char(2147483647)  NOT NULL,\r\n    [time] nvarchar(2147483647)  NOT NULL,\r\n    [da" +
            "te] nvarchar(2147483647)  NOT NULL\r\n);\r\n\r\n-- Creating table \'MemberSet\'\r\nCREATE " +
            "TABLE [MemberSet] (\r\n    [Id] INTEGER PRIMARY KEY NOT NULL,\r\n    [firstname] nva" +
            "rchar(2147483647)  NOT NULL,\r\n    [lastname] nvarchar(2147483647)  NOT NULL,\r\n  " +
            "  [middlenames] nvarchar(2147483647)  NOT NULL,\r\n    [mobile] nvarchar(214748364" +
            "7)  NOT NULL,\r\n    [email] nvarchar(2147483647)  NOT NULL,\r\n    [phone] nvarchar" +
            "(2147483647)  NOT NULL,\r\n    [sex] nvarchar(2147483647)  NOT NULL,\r\n    [birthda" +
            "te] nvarchar(2147483647)  NOT NULL,\r\n    [Address_Id] integer  NOT NULL,\r\n    [M" +
            "emberDetais_Id] integer  NOT NULL\r\n);\r\n\r\n-- Creating table \'ContactSet\'\r\nCREATE " +
            "TABLE [ContactSet] (\r\n    [Id] INTEGER PRIMARY KEY NOT NULL,\r\n    [firstname] nv" +
            "archar(2147483647)  NOT NULL,\r\n    [lastname] nvarchar(2147483647)  NOT NULL,\r\n " +
            "   [mobile] nvarchar(2147483647)  NOT NULL,\r\n    [email] nvarchar(2147483647)  N" +
            "OT NULL,\r\n    [phone] nvarchar(2147483647)  NOT NULL,\r\n    [Member_Id] integer  " +
            "NOT NULL,\r\n    [Address_Id] integer  NOT NULL\r\n);\r\n")]
        public string CreationString {
            get {
                return ((string)(this["CreationString"]));
            }
            set {
                this["CreationString"] = value;
            }
        }
    }
}
