//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Members", "MemberAddress", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database.Member), "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database.Address))]
[assembly: EdmRelationshipAttribute("Members", "MemberMemberDetais", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database.Member), "MemberDetais", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database.MemberDetais))]
[assembly: EdmRelationshipAttribute("Members", "MemberContact", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database.Member), "Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Database.Contact))]
[assembly: EdmRelationshipAttribute("Members", "ContactAddress", "Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Database.Contact), "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Database.Address))]

#endregion

namespace Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MembersContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MembersContainer object using the connection string found in the 'MembersContainer' section of the application configuration file.
        /// </summary>
        public MembersContainer() : base("name=MembersContainer", "MembersContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MembersContainer object.
        /// </summary>
        public MembersContainer(string connectionString) : base(connectionString, "MembersContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MembersContainer object.
        /// </summary>
        public MembersContainer(EntityConnection connection) : base(connection, "MembersContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> AddressSet
        {
            get
            {
                if ((_AddressSet == null))
                {
                    _AddressSet = base.CreateObjectSet<Address>("AddressSet");
                }
                return _AddressSet;
            }
        }
        private ObjectSet<Address> _AddressSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MemberDetais> MemberDetaisSet
        {
            get
            {
                if ((_MemberDetaisSet == null))
                {
                    _MemberDetaisSet = base.CreateObjectSet<MemberDetais>("MemberDetaisSet");
                }
                return _MemberDetaisSet;
            }
        }
        private ObjectSet<MemberDetais> _MemberDetaisSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Organization> OrganizationSet
        {
            get
            {
                if ((_OrganizationSet == null))
                {
                    _OrganizationSet = base.CreateObjectSet<Organization>("OrganizationSet");
                }
                return _OrganizationSet;
            }
        }
        private ObjectSet<Organization> _OrganizationSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Changelog> ChangelogSet
        {
            get
            {
                if ((_ChangelogSet == null))
                {
                    _ChangelogSet = base.CreateObjectSet<Changelog>("ChangelogSet");
                }
                return _ChangelogSet;
            }
        }
        private ObjectSet<Changelog> _ChangelogSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> MemberSet
        {
            get
            {
                if ((_MemberSet == null))
                {
                    _MemberSet = base.CreateObjectSet<Member>("MemberSet");
                }
                return _MemberSet;
            }
        }
        private ObjectSet<Member> _MemberSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> ContactSet
        {
            get
            {
                if ((_ContactSet == null))
                {
                    _ContactSet = base.CreateObjectSet<Contact>("ContactSet");
                }
                return _ContactSet;
            }
        }
        private ObjectSet<Contact> _ContactSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AddressSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddressSet(Address address)
        {
            base.AddObject("AddressSet", address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MemberDetaisSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMemberDetaisSet(MemberDetais memberDetais)
        {
            base.AddObject("MemberDetaisSet", memberDetais);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrganizationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganizationSet(Organization organization)
        {
            base.AddObject("OrganizationSet", organization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChangelogSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChangelogSet(Changelog changelog)
        {
            base.AddObject("ChangelogSet", changelog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MemberSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMemberSet(Member member)
        {
            base.AddObject("MemberSet", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContactSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContactSet(Contact contact)
        {
            base.AddObject("ContactSet", contact);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="address1">Initial value of the address property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="postalcode">Initial value of the postalcode property.</param>
        /// <param name="country">Initial value of the country property.</param>
        public static Address CreateAddress(global::System.Int64 id, global::System.String address1, global::System.String city, global::System.String postalcode, global::System.String country)
        {
            Address address = new Address();
            address.Id = id;
            address.address = address1;
            address.city = city;
            address.postalcode = postalcode;
            address.country = country;
            return address;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            internal set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String postalcode
        {
            get
            {
                return _postalcode;
            }
            set
            {
                OnpostalcodeChanging(value);
                ReportPropertyChanging("postalcode");
                _postalcode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("postalcode");
                OnpostalcodeChanged();
            }
        }
        private global::System.String _postalcode;
        partial void OnpostalcodeChanging(global::System.String value);
        partial void OnpostalcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberAddress", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberAddress", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberAddress", "Member").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberAddress", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("Members.MemberAddress", "Member", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "ContactAddress", "Contact")]
        public Contact Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("Members.ContactAddress", "Contact").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("Members.ContactAddress", "Contact").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contact> ContactReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("Members.ContactAddress", "Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contact>("Members.ContactAddress", "Contact", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="Changelog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Changelog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Changelog object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="action">Initial value of the action property.</param>
        /// <param name="newvalue">Initial value of the newvalue property.</param>
        /// <param name="oldvalue">Initial value of the oldvalue property.</param>
        /// <param name="memberid">Initial value of the memberid property.</param>
        /// <param name="time">Initial value of the time property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Changelog CreateChangelog(global::System.Int64 id, global::System.String action, global::System.String newvalue, global::System.String oldvalue, global::System.String memberid, global::System.String time, global::System.String date)
        {
            Changelog changelog = new Changelog();
            changelog.Id = id;
            changelog.action = action;
            changelog.newvalue = newvalue;
            changelog.oldvalue = oldvalue;
            changelog.memberid = memberid;
            changelog.time = time;
            changelog.date = date;
            return changelog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String action
        {
            get
            {
                return _action;
            }
            set
            {
                OnactionChanging(value);
                ReportPropertyChanging("action");
                _action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("action");
                OnactionChanged();
            }
        }
        private global::System.String _action;
        partial void OnactionChanging(global::System.String value);
        partial void OnactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String newvalue
        {
            get
            {
                return _newvalue;
            }
            set
            {
                OnnewvalueChanging(value);
                ReportPropertyChanging("newvalue");
                _newvalue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("newvalue");
                OnnewvalueChanged();
            }
        }
        private global::System.String _newvalue;
        partial void OnnewvalueChanging(global::System.String value);
        partial void OnnewvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String oldvalue
        {
            get
            {
                return _oldvalue;
            }
            set
            {
                OnoldvalueChanging(value);
                ReportPropertyChanging("oldvalue");
                _oldvalue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("oldvalue");
                OnoldvalueChanged();
            }
        }
        private global::System.String _oldvalue;
        partial void OnoldvalueChanging(global::System.String value);
        partial void OnoldvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String memberid
        {
            get
            {
                return _memberid;
            }
            set
            {
                OnmemberidChanging(value);
                ReportPropertyChanging("memberid");
                _memberid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("memberid");
                OnmemberidChanged();
            }
        }
        private global::System.String _memberid;
        partial void OnmemberidChanging(global::System.String value);
        partial void OnmemberidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.String _time;
        partial void OntimeChanging(global::System.String value);
        partial void OntimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="mobile">Initial value of the mobile property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static Contact CreateContact(global::System.Int64 id, global::System.String firstname, global::System.String lastname, global::System.String mobile, global::System.String email, global::System.String phone)
        {
            Contact contact = new Contact();
            contact.Id = id;
            contact.firstname = firstname;
            contact.lastname = lastname;
            contact.mobile = mobile;
            contact.email = email;
            contact.phone = phone;
            return contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            internal set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mobile
        {
            get
            {
                return _mobile;
            }
            set
            {
                OnmobileChanging(value);
                ReportPropertyChanging("mobile");
                _mobile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mobile");
                OnmobileChanged();
            }
        }
        private global::System.String _mobile;
        partial void OnmobileChanging(global::System.String value);
        partial void OnmobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberContact", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberContact", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberContact", "Member").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberContact", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("Members.MemberContact", "Member", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "ContactAddress", "Address")]
        public Address Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.ContactAddress", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.ContactAddress", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.ContactAddress", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("Members.ContactAddress", "Address", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="middlenames">Initial value of the middlenames property.</param>
        /// <param name="mobile">Initial value of the mobile property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="sex">Initial value of the sex property.</param>
        /// <param name="birthdate">Initial value of the birthdate property.</param>
        public static Member CreateMember(global::System.Int64 id, global::System.String firstname, global::System.String lastname, global::System.String middlenames, global::System.String mobile, global::System.String email, global::System.String phone, global::System.String sex, global::System.String birthdate)
        {
            Member member = new Member();
            member.Id = id;
            member.firstname = firstname;
            member.lastname = lastname;
            member.middlenames = middlenames;
            member.mobile = mobile;
            member.email = email;
            member.phone = phone;
            member.sex = sex;
            member.birthdate = birthdate;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            internal set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String middlenames
        {
            get
            {
                return _middlenames;
            }
            set
            {
                OnmiddlenamesChanging(value);
                ReportPropertyChanging("middlenames");
                _middlenames = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("middlenames");
                OnmiddlenamesChanged();
            }
        }
        private global::System.String _middlenames;
        partial void OnmiddlenamesChanging(global::System.String value);
        partial void OnmiddlenamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mobile
        {
            get
            {
                return _mobile;
            }
            set
            {
                OnmobileChanging(value);
                ReportPropertyChanging("mobile");
                _mobile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mobile");
                OnmobileChanged();
            }
        }
        private global::System.String _mobile;
        partial void OnmobileChanging(global::System.String value);
        partial void OnmobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.String _sex;
        partial void OnsexChanging(global::System.String value);
        partial void OnsexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String birthdate
        {
            get
            {
                return _birthdate;
            }
            set
            {
                OnbirthdateChanging(value);
                ReportPropertyChanging("birthdate");
                _birthdate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("birthdate");
                OnbirthdateChanged();
            }
        }
        private global::System.String _birthdate;
        partial void OnbirthdateChanging(global::System.String value);
        partial void OnbirthdateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberAddress", "Address")]
        public Address Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.MemberAddress", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.MemberAddress", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("Members.MemberAddress", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("Members.MemberAddress", "Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberMemberDetais", "MemberDetais")]
        public MemberDetais MemberDetais
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MemberDetais>("Members.MemberMemberDetais", "MemberDetais").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MemberDetais>("Members.MemberMemberDetais", "MemberDetais").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MemberDetais> MemberDetaisReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MemberDetais>("Members.MemberMemberDetais", "MemberDetais");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MemberDetais>("Members.MemberMemberDetais", "MemberDetais", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberContact", "Contact")]
        public EntityCollection<Contact> Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contact>("Members.MemberContact", "Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contact>("Members.MemberContact", "Contact", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="MemberDetais")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MemberDetais : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MemberDetais object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="memberno">Initial value of the memberno property.</param>
        /// <param name="memberclass">Initial value of the memberclass property.</param>
        /// <param name="membergroup">Initial value of the membergroup property.</param>
        /// <param name="memberjob">Initial value of the memberjob property.</param>
        /// <param name="joindate">Initial value of the joindate property.</param>
        /// <param name="exitdate">Initial value of the exitdate property.</param>
        /// <param name="changeddate">Initial value of the changeddate property.</param>
        /// <param name="paymentstatus">Initial value of the paymentstatus property.</param>
        public static MemberDetais CreateMemberDetais(global::System.Int64 id, global::System.String memberno, global::System.String memberclass, global::System.String membergroup, global::System.String memberjob, global::System.String joindate, global::System.String exitdate, global::System.String changeddate, global::System.String paymentstatus)
        {
            MemberDetais memberDetais = new MemberDetais();
            memberDetais.Id = id;
            memberDetais.memberno = memberno;
            memberDetais.memberclass = memberclass;
            memberDetais.membergroup = membergroup;
            memberDetais.memberjob = memberjob;
            memberDetais.joindate = joindate;
            memberDetais.exitdate = exitdate;
            memberDetais.changeddate = changeddate;
            memberDetais.paymentstatus = paymentstatus;
            return memberDetais;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            internal set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String memberno
        {
            get
            {
                return _memberno;
            }
            set
            {
                OnmembernoChanging(value);
                ReportPropertyChanging("memberno");
                _memberno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("memberno");
                OnmembernoChanged();
            }
        }
        private global::System.String _memberno;
        partial void OnmembernoChanging(global::System.String value);
        partial void OnmembernoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String memberclass
        {
            get
            {
                return _memberclass;
            }
            set
            {
                OnmemberclassChanging(value);
                ReportPropertyChanging("memberclass");
                _memberclass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("memberclass");
                OnmemberclassChanged();
            }
        }
        private global::System.String _memberclass;
        partial void OnmemberclassChanging(global::System.String value);
        partial void OnmemberclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String membergroup
        {
            get
            {
                return _membergroup;
            }
            set
            {
                OnmembergroupChanging(value);
                ReportPropertyChanging("membergroup");
                _membergroup = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("membergroup");
                OnmembergroupChanged();
            }
        }
        private global::System.String _membergroup;
        partial void OnmembergroupChanging(global::System.String value);
        partial void OnmembergroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String memberjob
        {
            get
            {
                return _memberjob;
            }
            set
            {
                OnmemberjobChanging(value);
                ReportPropertyChanging("memberjob");
                _memberjob = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("memberjob");
                OnmemberjobChanged();
            }
        }
        private global::System.String _memberjob;
        partial void OnmemberjobChanging(global::System.String value);
        partial void OnmemberjobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String joindate
        {
            get
            {
                return _joindate;
            }
            set
            {
                OnjoindateChanging(value);
                ReportPropertyChanging("joindate");
                _joindate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("joindate");
                OnjoindateChanged();
            }
        }
        private global::System.String _joindate;
        partial void OnjoindateChanging(global::System.String value);
        partial void OnjoindateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String exitdate
        {
            get
            {
                return _exitdate;
            }
            set
            {
                OnexitdateChanging(value);
                ReportPropertyChanging("exitdate");
                _exitdate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("exitdate");
                OnexitdateChanged();
            }
        }
        private global::System.String _exitdate;
        partial void OnexitdateChanging(global::System.String value);
        partial void OnexitdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String changeddate
        {
            get
            {
                return _changeddate;
            }
            set
            {
                OnchangeddateChanging(value);
                ReportPropertyChanging("changeddate");
                _changeddate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("changeddate");
                OnchangeddateChanged();
            }
        }
        private global::System.String _changeddate;
        partial void OnchangeddateChanging(global::System.String value);
        partial void OnchangeddateChanged();
    
        /// <summary>
        /// PaymentLeft
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String paymentstatus
        {
            get
            {
                return _paymentstatus;
            }
            set
            {
                OnpaymentstatusChanging(value);
                ReportPropertyChanging("paymentstatus");
                _paymentstatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("paymentstatus");
                OnpaymentstatusChanged();
            }
        }
        private global::System.String _paymentstatus;
        partial void OnpaymentstatusChanging(global::System.String value);
        partial void OnpaymentstatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Members", "MemberMemberDetais", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberMemberDetais", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberMemberDetais", "Member").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("Members.MemberMemberDetais", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("Members.MemberMemberDetais", "Member", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Members", Name="Organization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Organization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Organization object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="key">Initial value of the key property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static Organization CreateOrganization(global::System.Int64 id, global::System.String key, global::System.String value)
        {
            Organization organization = new Organization();
            organization.Id = id;
            organization.key = key;
            organization.value = value;
            return organization;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            internal set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String key
        {
            get
            {
                return _key;
            }
            set
            {
                OnkeyChanging(value);
                ReportPropertyChanging("key");
                _key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("key");
                OnkeyChanged();
            }
        }
        private global::System.String _key;
        partial void OnkeyChanging(global::System.String value);
        partial void OnkeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
    }

    #endregion

    
}
